import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
import { ToastContainer } from 'react-toastify';
import { ReduxProvider } from '@/redux/provider';
import { ThemeProvider } from '@/components/common/theme-provider';
import MenuBarNextComponent from '@/components/common/menu/menu';
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <ReduxProvider>
            <div className="w-full flex flex-col gap-4">
              <MenuBarNextComponent />
              <div className="py-4 centralized-center">{children}</div>
            </div>
          </ReduxProvider>
        </ThemeProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
